### PR TITLE
Interpolate outputReport file placeholders

### LINKED ISSUE #121: outputReport option writes report last file checked only
I am using an example configuration for `checkstyle.xml`. The issue is that the file generated contains style report just for the last file that was checked, not the aggregate of all the files checked by the `eslint-loader`. It kind of beats the purpose of storing the raport.

### PR DESCRIPTION
**Pull request by smokku**
Fixes #121

### CODE REVIEW

**Comment by smokku** [comment]
This change allows specifying `outputReport.filePath` as `checkstyle-[hash].xml` or `checkstyle-[name].xml`. This will generate separate checkstyle XML file for each linted file, which then can be gathered by reporter.

**Comment by MoOx** [comment]
Thanks!
Could you write a test for this please?

**Comment by deryni** [comment]
I wrote up some tests for this in PR #134 .

**Comment by MoOx** [comment]
So this PR should be closed in favor of #134 right?

**Comment by MoOx** [comment]
Closing in favor of #134

**Pull request closed without merging**
