### PR TITLE
added quiet filter.

### PR DESCRIPTION
**Pull request by antosop**
This is my first draft attempt at adding quiet functionality. It get's the job done, but I'm open to suggestions for a more elegant solution.

### CODE REVIEW

**Comment by MoOx** [comment]
If it works, it's better than nothing :)
Can you add a minimal test please ?

**Comment by MoOx** [comment]
Also update the README with this new option.

**Comment by antosop** [comment]
The test has been added and README has been updated.

**Comment by MoOx** [comment]
:+1:

**Comment by MoOx** [comment]
I will need some refactor for that since I need to change method used (`new CLIEngine().processOnText()` instead `linter.verify()`) to benefit of plugins support.
Hopefully before monday morning :)

**Pull request merged**
