### PR TITLE
Add eslintPath option

### PR DESCRIPTION
**Pull request by trungdq88**
This PR is originally created here https://github.com/MoOx/eslint-loader/pull/181, but due to an issue with eslint-mock.js, the test failed on master. I have fixed it.

Related to https://github.com/MoOx/eslint-loader/issues/153

Changes:
- Implemented 'eslintPath' option.
- Added test case.
- Documented.

### CODE REVIEW

**Comment by gaearon** [comment]
When this gets merged do you mind pinging me in https://github.com/facebookincubator/create-react-app/issues/2604?
Thanks!

**Comment by trungdq88** [comment]
@MoOx do you mind have a look at this? Thanks!

**Comment by MoOx** [comment]
Hi. I just get back from vacations so I have a tons of stuff to handle but I will try to have a look asap.

**Comment by MoOx** [comment]
Thanks! it's released as 1.9.0

**Comment by trungdq88** [comment]
Thanks 👍

**Pull request merged**
