### PR TITLE
Fixed: eslint range from 0.17 to 0.21 (0.11.2)

### PR DESCRIPTION
**Pull request by yamalight**

### CODE REVIEW

**Comment by MoOx** [comment]
Thanks !

**Comment by yamalight** [comment]
That was quick, thanks! :)

**Comment by MoOx** [comment]
Released !

**Comment by yamalight** [comment]
Awesome, thank you!

**Comment by MoOx** [comment]
Thank you. Not me.

**Comment by yamalight** [comment]
some people take quite much longer than this to merge and release, so I think it goes both ways :)

**Pull request merged**
