### PR TITLE
support eslint@4.x

### LINKED ISSUE #177: support eslint@4.x
eslint@4.x is comming, seems it didn't support?

### PR DESCRIPTION
**Pull request by Aladdin-ADD**
**What is the purpose of this pull request? (put an "X" next to item)**
[x] Other, please explain: support eslint@v4 (fixes #177 )

**What changes did you make? (Give an overview)**
* fix invalid eslint config.
* upgrade devDependencies & peerDependencies.
* fix eslint errors.

**Is there anything you'd like reviewers to focus on?**
* to fix `max-len` errors, change the config 80 to 120.
* update peerdep: eslint<4.0.0 to eslint<5.0.0, I'm not sure about it.

### CODE REVIEW

**Comment by MoOx** [comment]
where did you find errors? Is it related to latest version? Latest build was ok https://travis-ci.org/MoOx/eslint-loader/builds/217043093

**Comment by Aladdin-ADD** [comment]
@MoOx updated the `OP`.

**Comment by Aladdin-ADD** [comment]
ci failed on node@v4.

> npm ERR! peerinvalid The package eslint@4.0.0-rc.0 does not satisfy its siblings' peerDependencies requirements!

4.0.0-rc.0 < 5.0.0, why this error? I don't know much about the comparison.

**Comment by Aladdin-ADD** [comment]
@MoOx eslint@4.0.0 released. it seems all the tests passed. you can merge the PR. :)

**Pull request merged**
