### PR TITLE
Bump ESLint version

### PR DESCRIPTION
**Pull request by koistya**
Ref #41

### CODE REVIEW

**Comment by kentcdodds** [comment]
Yes, a more loose peerDep is preferred :-)

**Comment by MoOx** [comment]
Closed by 92b7a42c1792278604834cc2444596a5135de86d
Sorry for the delay :)

**Comment by kentcdodds** [comment]
is there a reason that the you specify such a strict `peerDependency`? It means that every time there's an `eslint` update, I have to wait for you to update your `peerDependency` before I can get it. I realize that maybe I'm just being impatient with free software, so sorry if it seems that way. It's just, as an OSS maintainer myself with libraries that have `peerDependencies` I also know the frustration that comes with having to have an entire release just to update dependencies, so I try to make the `peerDependencies` as loose as possible so people don't have to wait for me and I don't have to take the time to push an update just because the dep had a release.

**Comment by MoOx** [comment]
According to semver, 0.x can break API anytime. That's why. You should track eslint issue for 1.x. When we will have this one, only major bump will need a new release. It's their fault, not mine.
I just don't want people to come here and yell because the latest new version doesn't work with this module. 
It does not frustrate me, I take a minute to update if everything works fine. This time it was because I were waiting for a PR to be squashed so I can include it. Since this PR needed 0.21+, I didn't want to make 2 releases which changes the peerDep scope.
When it's "just a number", you can fork, change the number and use your fork for a few days, not a big deal.

**Comment by kentcdodds** [comment]
I understand. I guess it could go either way, you either have people upset because their waiting or you have people upset because they don't know how to manage their own dependencies properly. I'll be more patient in the future :+1: thanks for maintaining this project!

**Comment by MoOx** [comment]
> you either have people upset because their waiting 

like I said, the fork can take a 20sec :)

> or you have people upset because they don't know how to manage their own dependencies properly

I prefer to protect those people ^^

**Comment by kentcdodds** [comment]
Totally, I've forked projects before for that. I think you're wise to cater to the 90%

**Pull request closed without merging**
