### PR TITLE
Updates eslint from 0.14.1 to 0.15.0.

### PR DESCRIPTION
**Pull request by lancefisher**
Fixes MoOx/eslint-loader#6

### CODE REVIEW

**Comment by MoOx** [comment]
Thanks!

**Comment by MoOx** [comment]
fyi, I will work on the custom reporter option and release that today.

**Comment by lancefisher** [comment]
Cool, thanks!

**Comment by MoOx** [comment]
Released as 0.4 with a new default reporter and the custom reporter option. Enjoy.

**Pull request merged**
