### PR TITLE
a crack at solving #105

### PR DESCRIPTION
**Pull request by jameslnewell**

### CODE REVIEW

**Comment by jameslnewell** [comment]
Oh wait, I missed #106

**Comment by jameslnewell** [comment]
Reopening because #106 is only creating a new engine when a `configFile` prop is used. The config can also be passed as an object.

**Comment by jaythomas** [comment]
I like your more-robust solution over #106. One thing you might want to adjust however is the test: 

`"should report a single error because only one config causes an error"` does not infer that `"eslint-loader will create an engine for each unique config"`. Whether or not the second config is ignored, it will always report only one warning (not error). In my test I assured both configs were loading by throwing a unique warning from each: https://github.com/MoOx/eslint-loader/pull/106/files#diff-d1a0eb3a6e5c2e85a9cd54e5f92bfd7fR85

Feel free to borrow my solution or disregard!

**Comment by jameslnewell** [comment]
Thanks! 

Sorry, I'm not sure if I follow what you're saying... With my test, in the case where:
- the first eslint config is used for both instances, there will be 2 warnings generated (and we're expecting 1)
- the second eslint config is used for both instances, there will be 0 warnings generated (and we're expecting 1)
- no eslint configs are used, there will be 0 warnings generated (and we're expecting 1)

**Comment by jaythomas** [comment]
What I mean to say is [here](https://github.com/MoOx/eslint-loader/pull/123/files#diff-7a72bf3392b883ccdf77204df4412514R28), this rule will never throw an error so your assertion that `stats.compilation.warnings.length === 1` is always true even if that second config object is never loaded or if there were another unforeseen problem with the webpack settings. So the test doesn't directly verify that `"eslint-loader will create an engine for each unique config"` as your test is named.

My suggestion around this would be to change the second config object rule from `quotes: [1, "double"]` to something that will throw a second warning, (`semi: [1, "always"]` for instance). You will know the second config is loading correctly if it throws the expected warning from the second config. You can then change the assertion to read `stats.compilation.warnings.length === 2` instead of `=== 1`.

**Comment by jameslnewell** [comment]
Cool, I think I get you, however that introduces the problem where if only the first config is used, you'll still get two (quote) errors and the test will incorrectly pass. Do we need two separate tests? Got any ideas?

**Comment by jameslnewell** [comment]
^^checking that I get two different types of warnings

**Comment by jaythomas** [comment]
I have closed PR #106 in favor of this one.

**Comment by jameslnewell** [comment]
@MoOx thoughts?

**Comment by MoOx** [comment]
Great work!

**Comment by MoOx** [comment]
Releasing this as 1.6.1. Thanks you @jameslnewell and @jaythomas!

**Pull request merged**
