### PR TITLE
Upgrade to 0.12.0 and use `eslint/lib/config` to load config

### PR DESCRIPTION
**Pull request by jerrysu**
Upgrades to the current version of eslint.

Also, uses eslint's built-in ability to load configuration from `.eslintrc` and/or `package.json`.

### CODE REVIEW

**Comment by MoOx** [comment]
❤️
Next time let me take care of the bump when I handle the CHANGELOG :)

**Comment by MoOx** [comment]
Build is broken. Can you fix it so I can merge & release?

**Comment by jerrysu** [comment]
Oops. Looks like I should have ran the tests...

**Comment by MoOx** [comment]
While you are on it, can you update the CHANGELOG? Thanks!

**Comment by jerrysu** [comment]
Fixed lint issues, and updated CHANGELOG.md

**Comment by MoOx** [comment]
Cool. But for the CHANGELOG, you should do something like that 
https://github.com/cssnext/cssnext/blob/master/CHANGELOG.md

**Comment by jerrysu** [comment]
Ah, of course.. it's a changelog. Duh...

**Comment by jerrysu** [comment]
Sorry, it's too early in the morning for me and I haven't had any coffee yet. :)

**Comment by MoOx** [comment]
Well done. You are the best.

**Comment by MoOx** [comment]
[Released as 0.2.0](https://github.com/MoOx/eslint-loader/releases/tag/0.2.0)

**Pull request merged**
